### ISSUE TITLE
Possible incorrect selection of TFL scans for NYU subjects

### ISSUE THREAD

**Issue by Kyota-exe** [spinal-cord-7t/coil-qc-code#13] opened 2024-02-18 05:18 UTC
For each subject, we have a anat and famp TB1TFL scan. For MGH and MNI subjects, the `bids_conversion.py` script determines which scan is the anatomical scan and which scan is the flip-angle map scan by searching for the tokens `anatomical image` and `flip angle map` in the `ImageComments` attribute of the JSON. However, NYU subjects do not have this attribute in their JSON, and the information on what kind of TFL scan it is does not seem to appear anywhere in the JSON file. Since for MGH and MNI subjects, the anat scan is usually the first, and the famp scan is usually the third, this is what the `bids_conversion.py` script selects for NYU subjects. It is however likely that this is a mistake.

How should we differentiate TFL scans in NYU subjects to determine which one of them are the famp/anat scans?

**Comment by evaalonsoortiz** [comment] 2024-02-19 14:14
The NYU scans are acquired with a scanner of a different generation, so it's not surprising that there are some differences. I have looked at both TFL scans (anat and fmap) and both appear to be flip angle maps. My guess is that one is distortion corrected and the other is not (I do not know which would be which, they are too noisy to tell). There also appears to be slight differences in the noise (perhaps anat is noisier). @alanseifert Can you weigh in?

**Comment by alanseifert** [comment] 2024-02-19 15:01
I can only comment on what we get on our system (VB17): only a single
image, which is the flip angle map.

**Comment by evaalonsoortiz** [comment] 2024-02-19 16:03
@alanseifert These are the scans that were sent (or acquired) by you last summer for the THS 7T project. The turboFLASH scans all have two images, both of which appear to be flip angle maps. There are not identical. They are very noisy, so it's hard to tell, but my best guess is that one is distortion corrected and one is not. Could you perhaps verify with one of the datasets you have? It could be any one of the 3 subjects, they all have the 2 FSL images.

**Comment by Kyota-exe** [comment] 2024-02-19 16:28
I’m almost sure there’s more than 3 TFL scans outputted by the scanner for each NYU subject. The only reason there’s only 2 in the dataset I uploaded on the Google Drive is because my script naively assumes the first and third scans are the anat and famp scans respectively. 

Since it has been verified by @evaalonsoortiz that they are both flip-angle maps, I will upload later today the other TFL scan not included in the dataset, and we can verify that this missing one is the anat scan. I will then modify the `bids_conversion.py` script to include that one instead of the other flip-angle map scan.

**Comment by alanseifert** [comment] 2024-02-19 16:39
Hi Everyone,

I'm having a lot of trouble understanding the question.  Could you please
clarify what you're asking?

And you're asking about Mount Sinai data, not NYU, correct?  If this is
about the traveling spine study, NYU is not a member of that study.

**Comment by evaalonsoortiz** [comment] 2024-02-19 17:06
Hi @alanseifert, 

Yes, I'm referring to Mount Sinai data. For some reason @dpapp86 stored all Mount Sinai data under an "NYU" label on our servers. @dpapp86 Was this a mistake? I had not realized Mount Sinai is not affiliated with NYU, so that's probably what he did. We will change the label.

Here's a screenshot of some of your TFL dicom data, converted to nifti. As you can see, two images are output.

<img width="877" alt="Screen Shot 2024-02-19 at 12 03 27 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/c120f952-7c0d-4b69-89ce-219ad280e0d9">

When looking at those nifti images in FSL, both appear to be flip angle maps (see screenshots below). 
We haven't identified any header labels to help us differentiate between the two images.

<img width="1324" alt="Screen Shot 2024-02-19 at 12 04 15 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/6ac9facf-925f-49c3-988d-4494883faa1c">
<img width="1338" alt="Screen Shot 2024-02-19 at 12 04 31 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/0dcda0d2-04ca-4533-9f61-220892c4d4df">

**Comment by alanseifert** [comment] 2024-02-19 17:26
That looks different from the data I have locally.  Perhaps we used
different versions or command line options with dcm2niix?  I also have two
nifti's, but one has the two slice groups concatenated and another has only
one slice group (they must be manually re-interleaved).  See attached.

My only recommendation would be to investigate by starting again from
the DICOMs.

**Comment by evaalonsoortiz** [comment] 2024-02-19 17:26
> I’m almost sure there’s more than 3 TFL scans outputted by the scanner for each NYU subject. The only reason there’s only 2 in the dataset I uploaded on the Google Drive is because my script naively assumes the first and third scans are the anat and famp scans respectively.
> 
> Since it has been verified by @evaalonsoortiz that they are both flip-angle maps, I will upload later today the other TFL scan not included in the dataset, and we can verify that this missing one is the anat scan. I will then modify the `bids_conversion.py` script to include that one instead of the other flip-angle map scan.

@Kyota-exe I think you might be referring to something else. In the screenshot I included above, you can see that there are 4 types of TFL scans that were acquired. Two are with different saturation flip angles (60 vs. 90), and two with different reference voltages. 

The 90 degree saturation flip angle is the scan we want. The 60 degree saturation flip angle was acquired for another project. @alanseifert Can you confirm? Was the 60 degree saturation flip angle acquired for the fMRI or qMRI project? 

@Kyota-exe Once it is confirmed that the 60 degree saturation flip angle images are for another project, we will select between the two voltages. We want the image acquire with an "optimized" reference voltage. You can find what that reference voltage should be in table 2 here: https://docs.google.com/document/d/1rfxDTc-coK96GMKsx5_sBK_srCyuKY7BY51qRYrDmig/edit

The table indicates that the subject "Daniel" was scanned with voltages 450V and 680V, which does not correspond to the 300V and 450V shown in the screenshot (the screenshot is for subject Daniel).  @alanseifert Can you weigh in on which voltage we should be going with for assessing the flip angle map? This will likely come up again for other subjects.

**Comment by alanseifert** [comment] 2024-02-19 17:41
In my last e-mail I responded to the fact that there's two nifti's in each
of the 3-4 presatTFL directories, but yes, the different
presatTFL directories and separate acquisitions with the noted voltages and
saturation flip angles.  In some subjects (Daniel especially), the true
reference voltage is so high as to be impossible to acquire with saturation
FA = 90 and a correctly calibrated reference voltage, so in some cases, I
acquired with a decreased saturation FA = 60.

In your view, I also see that the scan directories have their acquisition
numbers stripped, which makes it more difficult to interpret which
presatTFLs are for which arm of the study.  Here, two are from the coilQA
arm, and one is from the fMRI arm.  There's probably also at least one
presatTFL from the qMRI arm as well, but I haven't merged the two sessions
in my local copy of the data.

Remember that I follow the green boxes in the SOP.  I'm unable to
automatically calibrate RefV, so I start with RefV = 300V and run a
presatTFL, then based on that, I calculate the actual calibrated RefV,
apply it, and re-acquire another presatTFL.  In this case, the calibrated
RefV was unachievable, so I used 450V, and at 450V, FA = 90 was
unachievable, so I used FA = 60.  It's up to you which one you want to use,
but because of these limitations, neither is exactly what your script is
probably expecting.

**Comment by alanseifert** [comment] 2024-02-19 18:34
That script is the one to recombine when a 56-slice scan is output, where
the two slices packets are concatenated side-by-side, and need to be
re-interleaved.  I've never encountered the case where two scans, each
having 28 slices, is output.

All of my preSatTFL scans have two nifti's output.  I think there's
something different between your nifti generation and mine, so I don't have
much confidence in recommending any specific method to interpret or
re-interleave them.  I think you'll have to open your nifti's, look at what
they contain, and determine from there what needs to be done.

**Comment by Kyota-exe** [comment] 2024-02-26 03:50
Optimal reference voltages for each subject in MtSinai:
Daniel: 680V
Laura: 350.3V
Rob: 436.9

The number of slices and the FA are taken from the .json, while the voltages are taken from the filenames.

Daniel:
**2x28 slices, FA 90, 300V** - (preSatTFL_sag_2p5mm_FOV320_RefV300V_satFA90)
**1x56 slices, FA 60, 450V** - (preSatTFL_sag_2p5mm_FOV320_RefV450V_satFA60)
**1x56 slices, FA 60, 450V** - (preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V)
**1x56 slices, FA 90, 300V** - (preSatTFL_satFA90_sag_2p5mm_FOV320_RefV300V)

Laura:
ERROR - (preSatTFL_sag_2p5mm_FOV320_RefV300V_satFA90)
ERROR - (preSatTFL_sag_2p5mm_FOV320_RefV354V_satFA80)
**1x56 slices, FA 79, 365V** - (preSatTFL_sag_2p5mm_FOV320_RefV365V)
**2x56 slices, FA 80, 350V** - (preSatTFL_satFA80_sag_2p5mm_FOV320_RefV350V)

Rob:
ERROR - (preSatTFL_sag_2p5mm_FOV320_RefV300V_satFA90)
ERROR - (preSatTFL_sag_2p5mm_FOV320_RefV440V_satFA60)
**1x56 slices, FA 60, 450V** - (preSatTFL_sag_2p5mm_FOV320_RefV450V_SatFA60)
**1x56 slices, FA 60, 450V** - (preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V)
**1x56 slices, FA 80, 350V** - (preSatTFL_satFA80_sag_2p5mm_FOV320_RefV350V)

Whenever it says ERROR, it's because `dcm2niix` fails to make the conversion and gives this error:
```
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 1 times
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
```

**Comment by dpapp86** [comment] 2024-02-26 11:55
My guess would be that the "Error" comes from the two slice packages of the acquisition not being properly offset. For example, if you move the FOV of slice group 1, but don't  move it for slice group 2, that could cause it.

If you open the "error" scans in a dicom viewer, is the inter-slice distance (the difference between the "position" values of the slices) constant?

**Comment by evaalonsoortiz** [comment] 2024-02-26 21:04
@dpapp86 I can confirm that for Laura's preSatTFL_sag_2p5mm_FOV320_RefV354V_satFA80 scan, that seems to be the case. I haven't checked the other scans that give errors.

@dpapp86 and @alanseifert In order to sort through all the refV and FA combinations and choose between them, it would be helpful to have the input of whomever acquired each scan.

Here's where I'm at (whoever scanned the subject in question, please let me know your thoughts):

**Subject: Daniel**

As per Alan's previous comments, I think it makes sense to keep the 450V and FA60 scan. 

There are two identical scans with those paramters: 
_preSatTFL_sag_2p5mm_FOV320_RefV450V_satFA60_ Can be discarded as it was acquired with an incorrect offset

_preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_ has the correct offset, but there are two dicom series associated with this scan. One has a series number 3, the other 37. There are very slight differences between the two, described in a post above (https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1952894006). Note that I am inspecting the DICOMS not the niftis this time. 

**Subject: Laura**

_preSatTFL_satFA80_sag_2p5mm_FOV320_RefV350V_ is the scan with refV that is closest to the calibrated value, I would perhaps go with this. However, this scan also has two series associated with it (series 2 and 3). Just like the _preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_ scan for Daniel, both series has two slice groups, with the correct offset, and minimal differences between the two.

**Subject: Rob**

These scans come with the following note:
_Calculated RefV was 491, used 450 instead... but I realized later that this calculation was incorrect because I assumed nominal saturation FA of 900, whereas it was actually 800.  The actual calculated RefV was 436.9 V, but I had already completed the entire protocol at RefV=450 by the time I realized this.  Scans are labeled with the reference voltage actually used._

I suppose it makes sense to keep the 450V/FA60 scan, given that everything else was acquired with 450V:

However, there are two seemingly identical scans to choose from. Why were two acquired? Both appear to have the correct slice thickness and slice gap.

preSatTFL_sag_2p5mm_FOV320_RefV450V_SatFA60
preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V

**Comment by dpapp86** [comment] 2024-02-28 11:26
I don't think I ever drove the scanner at Mt sinai, so I have to leave the issue to @alanseifert

**Comment by alanseifert** [comment] 2024-02-29 13:29
Some presatTFLs are for coilQA, some are for fMRI, and some are for qMRI.
You can check which series names correspond to which arms of the study by
looking at the PDF protocol exports.

I see the problem now for the qMRI presatTFL in Daniel's dataset.  There
must have been an errant click.  Slice group 1 has orientation S > T1.7,
slice group 2 is Sagittal.  Luckily there are so many presatTFLs to choose
from, and the ones in the coilQA and fMRI dataset don't have this issue.

Again, the answer to "why were two acquired" is because you have the entire
dataset, including two sessions, where one session is coilQA+fMRI and the
other is qMRI.  It looks like I used the ones that start with
preSatTFL_satFA60 in the coilQA+fMRI session, and the ones that start with
preSatTFL_sag_2p5mm in the qMRI session.

**Comment by evaalonsoortiz** [comment] 2024-03-06 18:08
@Kyota-exe Here is my conclusion for what we should keep (ie, convert to nifti and include in the BIDS formatted dataset):

**Daniel**
_preSatTFL_sag_2p5mm_FOV320_RefV450V_Sat60_ : this scan was not acquired in sagittal orientation (S>T1.7). Both slice groups appear to have the same orientation.
<img width="300" alt="Screenshot 2024-03-06 at 12 48 04 PM" src="https://github.com/spinal-cord-7t/coil-qc-code/assets/6652194/65777ed5-5403-4612-adbb-c585af81d47b">

The alternative scan (_preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_) has the issue I've documented above ([here](https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1965270613) and [here](https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1952894006). I have not been able to identify the cause of the issue, so I will discard the _preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_ scan for now. 

>  I see the problem now for the qMRI presatTFL in Daniel's dataset. There must have been an errant click. Slice group 1 has orientation S > T1.7, slice group 2 is Sagittal. 
> […](#)

I believe you are describing the _preSatTFL_sag_2p5mm_FOV320_RefV450V_Sat60_ scan, whereas I am talking about the _preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_ scan. 

**Laura**
_preSatTFL_satFA80_sag_2p5mm_FOV320_RefV350V_ : there are two scans with this exact same name, both are part of the coilQA leg of the study. One is series 2, the other series 3. Since they appear to be identical, we can arbitrarily go with series 2.

**Rob**
_preSatTFL_satFA60_sag_2p5mm_FOV320_RefV450V_ : This was an easier choice, there are more scans to choose from for this subject and all appear to be acquired with the correct parameters.

**Comment by Kyota-exe** [comment] 2024-03-08 04:20
Thank you. For Mt_Sinai subjects we won't have any anatomical TFL scans then?

**Comment by alanseifert** [comment] 2024-03-08 11:25
I'm still not sure what you mean by TFL anatomicals.  Our TFL sequence
produces only a map.

**Comment by dpapp86** [comment] 2024-03-08 12:15
But on Terra systems, you also get an anatomical, GRE-like contrast image,
not just the B1+ maps. I'm guessing this is what Kyota is looking for

**Comment by evaalonsoortiz** [comment] 2024-04-30 23:30
This issue has been resolved as per https://github.com/spinal-cord-7t/coil-qc-code/issues/13#issuecomment-1981499263

**Closed by evaalonsoortiz** 2024-04-30 23:30 UTC
